name: 'A Friendly Dragon'
description: 'Dragon greeter'
inputs:
  dragonDescription: 
    description: What is this dragon doing?
    required: true
    default: 'flying'
outputs:
  time:
    description: 'The time the dragon greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dragonDescription }}